### ISSUE TITLE
Modify docs.

### ISSUE THREAD

**Issue by Carreau** [phosphorjs/phosphorjs.github.io#2]
Checkout the `source` branch. 

Modify markdown files in src, make a PR or push  on the source branch, and ping me. 

Deployed [here](http://phosphorjs.github.io/about/) for now.

**Comment by sccolbert** [comment]
I don't completely follow you. Is that "checkout" as in "hey, take a look at this", or "checkout" as in you actually need me to git checkout the branch and make some edits? 

I'm assuming it's the first option. It's awesome, and you're awesome, and I appreciate the help!

**Comment by Carreau** [comment]
Yep, it's checkout as `git checkout`. 

Just dump markdown file in `src`, they will be auto-listed, (except index.md, that makes the index page)
and create a section in `phosphorjs.github.io/<filename>`.

I'll tweek phosphor.js itself to push the doc on the `/api/` route  regularly.

You can directly `git push origin source:source` and Travis take care of rebuilding.

**Comment by sccolbert** [comment]
sweet
