### ISSUE TITLE
Example index gone

### ISSUE THREAD

**Issue by Carreau** [phosphorjs/phosphorjs.github.io#4]
Investigate. 

I launched a rebuild of the site just in case.

**Comment by jasongrout** [comment]
FYI, the example index is there now, but the links don't work: http://phosphorjs.github.io/examples/

**Comment by Carreau** [comment]
Yep, strip the underscore in the address, I already have a PR on phosphor that fixes that. 

The problem is that both this repo and phosphor itself write to /example/ and clean in phosphor remove the index generated by this.

**Comment by sccolbert** [comment]
I'm not sure I understand what the issue is. What directory is trying to be written by both?

**Comment by sccolbert** [comment]
@Carreau  Also, why is the travis.yml pointed at your repo?

**Comment by Carreau** [comment]
> @Carreau Also, why is the travis.yml pointed at your repo?

This is a mistake. 

> I'm not sure I understand what the issue is. What directory is trying to be written by both?

1) `phosphorjs/phosphorjs.github.io` build the example index in `examples/index.html`
2) `phosphorjs/phosphor`  build the examples docs in `examples/<folders>/index.html`

When 2) happend it erases the index.html of 1), but 1 does not erase 2) .

I can work around that if I get a clean build of the all docs in phosphor itself.

**Comment by sccolbert** [comment]
If I understand correctly, these are building in different repos, and hence different VMs. Where does the conflict arise?

**Comment by Carreau** [comment]
There is basically 2 repo and 3 branches.

**Comment by Carreau** [comment]
(sorry miss submit, will write description and repost)

**Comment by Carreau** [comment]
there is basically 2 repo, 3 branches. 
- phosphor/master
- website/source
- website/master

`website/master` is deployed on gh-pages.

Every push on `website/source` triggers travis: clone `website/master` update the static content generated from markdown files, commit the changes, and push back on `website/master`. 

Every push on `phosphor/master` triggers travis: clone `website/master` update `/docs/` (by running typedocs) and (/examples/) content commit the changes and push back. 

Both are just trying to update `/examples/`.
