### ISSUE TITLE
Can't Use Jinja Template in Phosphor JS

### ISSUE THREAD

**Issue by syammil000** [phosphorjs/phosphorjs.github.io#44]
Hello,

I want to ask something,

I'm developing a flask web application right now and want to merge the Phosphor JS with it but I can't seem to use jinja template such as {% include 'abc.html' %} or {%extends 'abc.html' %} . When I put it, the page just become blank.

Do you have any solution for this or flask is not compatible with Phosphor JS ?

**Comment by sccolbert** [comment]
Please ask this question on the main Phosphor repo:
https://github.com/phosphorjs/phosphor
