### ISSUE TITLE
What about using Jekyll for site generation?

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphorjs.github.io#7]
@Carreau  Since Github runs Jekyll automatically anyway, what do you think about leveraging that for the website build? I'm thinking (perhaps naively at this point) that we could build the api docs on the phosphor travis bot, then check them in to master in this repo into a `_api` directory (or something similar). The static pages could still be authored in `master` in other `_` dirs. This will remove the need for two branches in this repo, as well as the `gh-pages` branch in phosphor. Thoughts?

Update: erm, I mean non underscore dirs, so that it works with this: http://jekyllrb.com/docs/structure/

**Comment by sccolbert** [comment]
Actually, we don't even need to check-in the api docs here, since they are automatically hosted at `phosphorjs.github.io/phosphor`, we just need to link to them from the static site.

**Comment by Carreau** [comment]
Hum, we can try to do that. I'm not familiar with jekyll,  and  it look much more targetted to a blog than docs, but we can give it a try too. I'll play around.

**Comment by sccolbert** [comment]
Just to be clear, I wasn't asking you to do the work. I'm going to fiddle with it tonight. I was just soliciting your opinion.

**Comment by Carreau** [comment]
Well, I looked at jekyll around, and it seemed painful to find a out of the box things that do what we want.
But you might have a better luck than I.

Also as you need to install ruby to test locally, I quickly moved away from it.

**Comment by sccolbert** [comment]
Ah, okay.

However, I still think we don't need to push the generated api docs to this repo. We should just be able to link to them as needed, yes?

**Comment by Carreau** [comment]
Yes, we can link, seem like a good plan.
